#!/usr/bin/env python
import rospy
from vehicle_controllers.algorithm import SteeringMethods
from vehicle_controllers.utility import RosCallbackDefine
import pdb


#### TO CHANGE ROS WORKING DIRECTORY
#### export ROS_HOME=$HOME 
#### CHANGE IN package.xml file

#### USAGE
#    SIMPLY IMPORT OR CREATE AN INSTACE OF CLASS LongController
#    or run it 
		
class LatController:
   def __init__(self):
	wpfile = rospy.get_param('waypoints_file',"odom_waypoints.dat")
	vehicle = rospy.get_param("vehicle","POLARIS")
	#### CREATE SteeringFeedForward Object. Pass in the waypoints
	steeringFF = SteeringMethods(wpfile,lookAhead=10.0,wheelBase=2.4,steeringRatio=12)	#Using default mkz values, otherwise specify them: lookAhead = 10.0, wheelBase = 2.85, steeringRatio = 14.8
	topic_helper = RosCallbackDefine(vehicle)		
	#### CREATE LOOP 
	rate=rospy.Rate(50)
	while not rospy.is_shutdown():
		# methodPurePursuit function 
		# will use default values, otherwise specify them: lookAhead=self.LA,WheelBase=self.WB,SteeringRatio=self.SR
		# Returns steercmd, curv, eastingBearing,relativeBearing, self.targetPoint
		states = topic_helper.return_states()
		if len(states) > 1:
			linearX = states[0]
			pose_x = states[1]
			pose_y = states[2]
			yaw = states[3]
			steercmd, curv, absoluteBearing, relativeBearing, targetPoint = steeringFF.methodPurePursuit(pose_x,pose_y,yaw)		# Calculate steering 
			
			steercmd_f = self.sat_limit(steercmd,-7.5,7.5)
			topic_helper.publish_vehicle_lat(steercmd)									# Publish the steering cmd	
		rate.sleep()


   def sat_limit(self,val,low,upper):
		if val >= upper:
			return upper
		elif val <= low:
			return low
		else:
			return val

    
if __name__=="__main__":
    rospy.init_node("lat_controller_node")
    try:
        latcontroller = LatController()
    except rospy.ROSInterruptException:
        pass


    


