#!/usr/bin/env python
import rospy
from vn300.msg import ins
from std_msgs.msg import Float64
import numpy as np
global velN, velX,flag
flag = 0
def vel_cb(msg):
	global velN, velX, flag
	velN = msg.NedVel.y
	velX = msg.NedVel.x
	flag = 1
rospy.init_node("TESTER")
velsub = rospy.Subscriber("/vectornav/ins",ins,vel_cb)
velpub = rospy.Publisher("/vectornav/veltest",Float64,queue_size=1)

pubSpeedMsg = Float64()
rate = rospy.Rate(50)
while not rospy.is_shutdown():
	if flag == 1:
		pubSpeedMsg.data = np.sqrt(velN**2 + velX**2)	
		velpub.publish(pubSpeedMsg)
		print pubSpeedMsg.data
	rate.sleep()
