# Polaris Parameters
lookAhead: 10.0
wheelBase: 2.87
steeringRatio: 16.0
steerLim:
 lower: -7.5
 upper: 7.5
# PID GAINS
# large error throttle
PID1:
 P: 0.024
 I: 0.0010
 D: 0.002
# large error brake
PID2:
 P: 0.0001
 I: 0.
 D: 0.
# small error brake
PID3:
 P: 0.
 I: 0.
 D: 0.
# Tolerance
Tol: 0.1
Adaptive:
 lMin: 5.
 lMax: 15.
 vMin: 3
 vMax: 6
 gamma: 0.75
 ayLim: 0.5

